### ISSUE TITLE
datachart-categoryhighlightlayer.adoc

### ISSUE THREAD

**Issue by pamelabrasil** [Infragistics/convertwire#34] opened 2015-11-11 20:58 UTC
Required background information does not appear in a table
In this Topic information is missing
First sentence of Category highlight layer overview text appears as- xamDataC__hart control
Samples information is missing

**Comment by ig-ealbert** [comment] 2015-11-12 20:21
The first two might be related, maybe some bad HTML?
The first sentence issue is a content issue.  It should be logged in TFS if Craig decides that a regex cleanup is not going to work.  See issue #28 for his comments about that.
The samples information is a duplicate of #37.

**Comment by craigshoemaker** [comment] 2015-11-23 20:56
All the items noted here are fixed except for the underscore in xamDataC__hart. This should be fixed in the source document manually. I have added it to the fix list.

**Closed as completed by craigshoemaker** 2015-11-23 20:56 UTC
Labels: fix-in-DocX

**Comment by ig-ealbert** [comment] 2016-05-12 19:30
Looks like this was also fixed in TFS 210073.
