### ISSUE TITLE
[XAML] {Warning} tag should not be visible as content

### ISSUE THREAD

**Issue by Teodor-Tenev** [Infragistics/convertwire#145] opened 2016-04-14 14:34 UTC
**Steps to reproduce:**
1. Open wpf/topics/xamribbon-display-custom-key-tips.adoc in LiveWire 
2. Observe
**Actual Result**:
{Warning} tag is visible as content
**Expected Result**:
{Warning} tag should not be visible as content

**Comment by ig-ealbert** [comment] 2016-04-14 16:34
Duplicate of #84.
https://github.com/Infragistics/convertwire/issues/84

**Closed as completed** 2016-04-15 08:00 UTC
Labels: bug
