### ISSUE TITLE
android-adding-linear-gauge - Overview step#1 needs to be moved to new line - bug

### ISSUE THREAD

**Issue by ghost** [Infragistics/convertwire#239] opened 2016-04-22 00:33 UTC
Step#1 of the overview section should start on a new line.

![image](https://cloud.githubusercontent.com/assets/14225200/14728133/3b8cc974-0800-11e6-8fa3-2a8685bf5d06.png)

**Comment by ig-ealbert** [comment] 2016-05-12 21:13
This is a duplicate of #238.

**Comment by craigshoemaker** [comment] 2016-05-19 19:25
Closed as duplicate

**Closed as completed by craigshoemaker** 2016-05-19 19:25 UTC
Labels: fix-in-DocX

**Comment by ig-ealbert** [comment] 2016-05-19 20:39
Logged TFS 219617 and fixed.
