### ISSUE TITLE
data-chart-create-chart-in-ms-blend - Overview hyperlink contains a stray link without a destination - bug

### ISSUE THREAD

**Issue by ghost** [Infragistics/convertwire#234] opened 2016-04-21 22:36 UTC
Link _Ref96219285 does not have a destination and needs to be removed as it appears as part of the topic.

![image](https://cloud.githubusercontent.com/assets/14225200/14726358/a216db5a-07ef-11e6-94d1-f4a1765d0767.png)

**Comment by ig-ealbert** [comment] 2016-04-25 15:40
This is not a bug with Convertwire.  You can log a bug in TFS for Pam or Mike D, as this happens in the HTML as well.

```
<a href="#_Ref397371182"><span class="ig-italic">Overview</span></a><a href="#_Ref396219285"></a>
```

http://help.staging.infragistics.local/Help/Doc/WPF/2016.1/CLR4.0/html/DataChart_Creating_Chart_In_MS_Blend_XAML.html
View the frame source and you'll see it.

**Comment by ig-ealbert** [comment] 2016-05-06 18:32
@ckearse : It looks like you fixed this in TFS in changeset 572613 for bug 218695.  If that's the case, then this github issue can be closed.  In general, bugs that exist prior to the asciidoc conversion (ex. they exist in the 16.1 documentation in Document X or in the online help) should be logged only in TFS, as it has nothing to do with Convertwire.

**Comment by craigshoemaker** [comment] 2016-05-19 13:24
this was fixed in TFS

**Closed as completed by craigshoemaker** 2016-05-19 13:24 UTC
