### ISSUE TITLE
Introduction section is missing

### ISSUE THREAD

**Issue by ig-ealbert** [Infragistics/convertwire#77] opened 2015-12-29 23:37 UTC
Open ig-excel-engine-changing-the-default-font.adoc in Livewire.
Observe the "Introduction" section, right above the Code example.
Compare with the online help.
http://help.infragistics.com/doc/Silverlight?page=IG_Excel_Engine_Changing_the_Default_Font.html
The Introduction section is missing, probably because it has a table with no header content?
The content is missing from the .adoc file.

**Comment by craigshoemaker** [comment] 2016-01-19 23:57
You're right that the issue is because of the empty table header. Closed by 9e2a727177c3d24e3ff1fe56abae40b751a48994

**Closed as completed by craigshoemaker** 2016-01-19 23:57 UTC
