### ISSUE TITLE
datachart legend topic contains + before table properties

### ISSUE THREAD

**Issue by IGvaleries** [Infragistics/convertwire#195] opened 2016-04-18 17:30 UTC
file: datachart-legends.adoc
in type of legends table item legend and scale legend appear with + in front
![converted](https://cloud.githubusercontent.com/assets/18487709/14613284/b2a034fe-0569-11e6-8076-31ba9919527c.PNG)

**Comment by craigshoemaker** [comment] 2016-05-06 21:14
This was resolved via a previous commit

**Comment by pamelabrasil** [comment] 2016-06-08 21:00
Item legend is not bulleted

**Comment by ig-ealbert** [comment] 2016-06-08 21:21
The issue that @pamelabrasil points out may be a duplicate of #257.

**Closed as completed** 2016-06-24 17:23 UTC
