### ISSUE TITLE
lineargauge-configuring-the-ranges - third table appears with incorrect column order and incorrect column headers - bug

### ISSUE THREAD

**Issue by ghost** [Infragistics/convertwire#241] opened 2016-04-22 00:56 UTC
The Property settings table does not have the correct column order, headers are incorrectly titled.

![image](https://cloud.githubusercontent.com/assets/14225200/14728475/1710cb42-0803-11e6-95e5-c86b15b5daba.png)

**Comment by ig-ealbert** [comment] 2016-05-12 21:14
This is a duplicate of #240 and other bugs that have been submitted.  Definitely a bug and needs to be fixed, but might be fixed by another commit.

**Comment by craigshoemaker** [comment] 2016-05-19 20:44
This is a complex table (merged cells) and it will be picked up by the tables report.

**Closed as completed by craigshoemaker** 2016-05-19 20:44 UTC
