### ISSUE TITLE
datachart - Category Stacked Bar series

### ISSUE THREAD

**Issue by mddifilippo89** [Infragistics/convertwire#217] opened 2016-04-20 20:57 UTC
1. Missing code snippets in preview pane for xaml, vb and C# where applicable.

**Comment by ig-ealbert** [comment] 2016-05-04 22:08
Duplicate of #202, #203, #204, among others.

**Comment by craigshoemaker** [comment] 2016-05-04 22:34
Same issue as #203

**Closed as completed by craigshoemaker** 2016-05-04 22:34 UTC

**Comment by mddifilippo89** [comment] 2016-06-10 20:30
Code snippets are now present. Duplicate code snippets remain.
