### ISSUE TITLE
datachart-docking-legends.adoc code sample missing.

### ISSUE THREAD

**Issue by agoldenbaum** [Infragistics/convertwire#242] opened 2016-04-22 18:44 UTC
Code sample is missing in docking legends topic. Namespace definitions are there, but XAML code does not render in LiveWire document.

**Comment by ig-ealbert** [comment] 2016-05-12 21:20
This may be caused by `ifdef::xaml-xf-ex[]` appearing above the section of XAML code snippets.  Livewire right now doesn't support showing code snippets if they're if-defed as something underneath another if-def.  Ex.

```
ifdef::xaml-xf-ex[]

*In XAML:*

ifdef::sl[]
```

This has been discussed in other issues and I think the goal is to have Livewire display build-flagged content based on the target product, not the individual build-flags.  For example, display the topic "as if it were the WPF version", not "with only WPF build flags".  This would include things like "xaml-xf-ex" in "wpf".  See #202 and #203.  @craigshoemaker is aware of this issue.

**Comment by craigshoemaker** [comment] 2016-05-19 18:54
closing this as a duplicate. Livewire will soon support product-based build flags and this issue will go away.

**Closed as completed by craigshoemaker** 2016-05-19 18:54 UTC
