### ISSUE TITLE
datagrid - Category Line Series topic

### ISSUE THREAD

**Issue by mddifilippo89** [Infragistics/convertwire#214] opened 2016-04-20 20:56 UTC
1. Extra "*" around Related Topics - making it bold for no reason.
2. Missing code snippets in preview pane for xaml, VB and C# where applicable.

**Comment by ig-ealbert** [comment] 2016-05-04 22:01
Part 1 can be fixed in the Document X file.

```
<UL>
<LI><A href="#Introduction"><STRONG>Introduction</STRONG></A> 
<LI><A href="#SeriesPreview"><STRONG>Series Preview</STRONG></A> 
<LI><A href="#SeriesRecommendations"><STRONG>Series Recommendations</STRONG></A> 
<LI><A href="#DataRequirements"><STRONG>Data Requirements</STRONG></A> 
<LI><A href="#DataRenderingRules"><STRONG>Data Rendering Rules</STRONG></A> 
<LI><A href="#DataBindingExample"><STRONG>Data Binding Example</STRONG></A> 
<LI><STRONG><A href="#RelatedTopics">Related Topics</A></STRONG> </LI></UL>
```

Note how the `<STRONG>` tag is outside of the `<A>` tag, which causes this behavior.  Theoretically all of the options should be bolded, but at least it should be consistent however it's handled.
I'll leave it up to Craig, but you might want to log a bug and fix it in DocX.
Part 2 is a duplicate of many other issues including #202, #203, #204.

**Comment by craigshoemaker** [comment] 2016-05-04 22:34
Part one is resolved by 88c9be1c6b6fe36b99106e570d245f89e7531cf1 and part two is a duplicate of #203

**Closed as completed by craigshoemaker** 2016-05-04 22:34 UTC

**Comment by mddifilippo89** [comment] 2016-06-07 19:58
Verified - fixed

**Comment by mddifilippo89** [comment] 2016-06-10 20:16
Everything is displayed correctly now but as a result build flag issues are present and known.
