### ISSUE TITLE
[XAML] Automatic character sequence conversion not required

### ISSUE THREAD

**Issue by rmkrmk** [Infragistics/convertwire#164] opened 2016-04-15 07:27 UTC
The following character sequences are converted to some special characters which is not required (and wrong).
- Character sequence “<=” wrongly converted to character “⇐”
- Character sequence “->” wrongly converted to character “→”

**Comment by craigshoemaker** [comment] 2016-04-25 21:45
@rmkrmk can you please provide some file names to reproduce with?

**Comment by rmkrmk** [comment] 2016-04-26 06:03
For the first issue:
commoncontrols.zip / ig-math-working-with-matrices.adoc

For the second issue:
commoncontrols.zip / using-infragistics-color-tuner.adoc

**Comment by craigshoemaker** [comment] 2016-04-29 20:45
This is an interesting one. The problem isn't in the conversion logic, but rather how AsciiDoc renders the character sequences as noted above. The fix for this is to surround these characters with `$$` to escape the characters from processing by AsciiDoc.

I will add a check for these types of sequences in the post conversion report so the escape characters can be fixed after the final conversion.

**Closed as completed** 2016-04-29 20:45 UTC
Labels: bug

**Comment by rmkrmk** [comment] 2016-06-10 09:46
Craig, where is this "post conversion report" located so I can check if there are warnings inside?

**Comment by ig-ealbert** [comment] 2016-06-10 13:55
@rmkrmk - commoncontrols\patterns\operator-character-sequences

**Comment by rmkrmk** [comment] 2016-06-13 07:31
Verified
