### ISSUE TITLE
# characters in mask are interpreted as asciidoc

### ISSUE THREAD

**Issue by ig-ealbert** [Infragistics/convertwire#109] opened 2016-01-12 20:40 UTC
Open xaminputs-masks.adoc.  Observe the first data row in the table.
`#` is interpreted as a styling syntax and as such, is not properly rendered.  I thought that I had logged this as an issue already but I couldn't find it.
Compare with online help:
http://help.infragistics.com/doc/WPF/2015.2/?page=xamInputs_Masks.html

**Comment by craigshoemaker** [comment] 2016-01-18 22:59
This appears to be fixed with recent changes. Not sure with commit is responsible though :smile:

**Comment by craigshoemaker** [comment] 2016-02-09 22:09
still an issue per @ig-ealbert

**Comment by craigshoemaker** [comment] 2016-02-10 17:50
Okay now I see what the issue is - I was previously looking at the first `#` value and how it rendered in the **Mask Character** column. The actual issue is a bit of a one-off problem so I can fix this issue with a fairly specific regular expression, but content like this that falls outside the pattern of a fake telephone number won't be caught.

**Closed as completed** 2016-02-10 17:57 UTC
