### ISSUE TITLE
All images are converted as block images

### ISSUE THREAD

**Issue by ig-ealbert** [Infragistics/convertwire#223] opened 2016-04-20 21:57 UTC
(Low priority)
Convert any R+ Desktop topic from AsciiDoc to HTML and back.
All images become block images like:
`(image::images/ActionsMenu_icon.png[ActionsMenu_icon])`
Inline images (which don't happen much in other products) become block images (extra `:`).
If possible, inline images should remain as inline by examining the elements around it.
For now it's ok to default to block images.
They render as text when they're inline.

**Comment by jVanZwieten** [comment] 2016-04-21 15:30
Is this the same thing ?
whats-new-whats-new-in-2015-volume-1.adoc
http://help.infragistics.com/doc/TestAutomationIBMWinForms/2015.2?page=Whats_New_Whats_New_in_2015_Volume_1.html

![imagewrong](https://cloud.githubusercontent.com/assets/16783024/14714807/751ba17a-07b4-11e6-8b21-a2758ed05953.PNG)

**Comment by ig-ealbert** [comment] 2016-04-21 15:32
Yes!
Block images use 2 colons (image::images/...).  Inline images use one colon (image:images/...).
I'll leave it to @craigshoemaker to confirm but this is similar to what I saw when I logged this issue.  The block images in tables appear as text.

**Comment by jVanZwieten** [comment] 2016-04-21 15:36
This is a duplicate of #155 .

**Comment by ig-ealbert** [comment] 2016-04-21 15:50
Yes, it does seem to be so.  I added a comment to #155 that the images seem to render correctly when using the inline syntax.
http://help.jp.staging.infragistics.local/reportplus/getting-started

**Comment by ig-ealbert** [comment] 2016-06-02 15:48
This is not resolved in the fix for #155.  The images are still converted as block elements.

**Closed as completed** 2017-01-27 22:12 UTC
