### ISSUE TITLE
[ta-rft] quotations converted to " BOLD QUOTATIONS "

### ISSUE THREAD

**Issue by jVanZwieten** [Infragistics/convertwire#233] opened 2016-04-21 15:56 UTC
//reproduce
winpivotgrid-using-pivotgrid-control-proxy.adoc
http://help.infragistics.com/doc/TestAutomationIBMWinForms/2015.2?page=WinPivotGrid_Using_PivotGrid_Control_Proxy.html

//result
![quotebold](https://cloud.githubusercontent.com/assets/16783024/14715676/9c7d7344-07b7-11e6-82db-11fb13da0c30.PNG)

//expected
![quoteboldexpected](https://cloud.githubusercontent.com/assets/16783024/14715681/a12ec104-07b7-11e6-9139-14db243e4701.PNG)

**Comment by ig-ealbert** [comment] 2016-05-04 21:00
There are bold spans in the source HTML.
`<span class="ig-bold">“PLUS_MINUS”</span>`
`“<span class="ig-bold">H2 CY 20002</span>”`
This is something that should be fixed in Document X.  Log a bug in TFS.
For reference:
`<meta name="TopicID" content="b1a1a142-4b3b-4d6c-99c4-af02a7c5afc7"/>`

**Comment by craigshoemaker** [comment] 2016-05-18 22:27
added `fix-in-DocX` label

**Closed as completed by craigshoemaker** 2016-05-18 22:27 UTC
Labels: fix-in-DocX

**Comment by ig-ealbert** [comment] 2016-05-19 14:55
Created TFS 219595 and am asking for feedback to see how to proceed.

**Comment by ig-ealbert** [comment] 2016-05-19 15:34
Noticed that the stylesheet for the TA IBM help is practically empty.  That's the reason why the styling is not showing up on the online help. $/NetAdvantage/DEV/WinForms/2016.2/TA/RFT/ProductGuidance/Topics/Product/stylesheets

**Comment by ig-ealbert** [comment] 2016-05-19 15:54
I checked with Mike Germann about the expected result.  Since the HTML has the `<span class="ig-bold">`, we decided it should indeed be bold.  The problem is that the IBM help stylesheet is almost empty.  When we move over to the Tripwire help viewer, a new stylesheet will be applied that should properly style the content.  As such, the bold should not be removed.
@craigshoemaker : Could you please remove the "fix-in-DocX" tag here?  The real bug is the missing CSS in the stylesheet, which will be fixed with the migration to Tripwire.
