### ISSUE TITLE
bulletgraph configuring the scale - extra text in link / duplicate sample names

### ISSUE THREAD

**Issue by IGvaleries** [Infragistics/convertwire#211] opened 2016-04-19 20:37 UTC
file: bulletgraph-configuring-the-scale.adoc

1) The section "Configuring the Scale's Label" contains malformed link: [_Configuring_the_Scale%E2%80%99s]configuring the scale’s value range.) 

![converted](https://cloud.githubusercontent.com/assets/18487709/14653649/ef36c124-0647-11e6-9a14-32b34ff13b3d.PNG)

2) sample names are duplicated in WPF :
![converted](https://cloud.githubusercontent.com/assets/18487709/14654452/b8723110-064b-11e6-8b0c-6d4c4b38d92d.PNG)

**Comment by ig-ealbert** [comment] 2016-05-04 17:00
For the first item, this is another issue with the content itself.

```
(This requires <a href="#_Configuring_the_Scale%E2%80%99s"></a><a class="ig-topic-link" href="#_Ref362967447">configuring the scale’s value range</a>.)
```

This can be fixed in the Document X files.  Submit a TFS bug and I can fix it.

For the second item, this is a duplicate of #209.

**Comment by craigshoemaker** [comment] 2016-05-11 17:28
I verified that d52662c675eb9b2a16ca7d9b8ed895cc3ceac5bb closes the second part of this issue. I will also label to fix in DocX for the first part.

**Closed as completed by craigshoemaker** 2016-05-11 17:28 UTC
Labels: bug, fix-in-DocX

**Comment by ig-ealbert** [comment] 2016-05-12 16:30
TFS 219326.  Fixed.
